vich_uploader:
  db_driver: orm

  mappings:
    image_articles:
      uri_prefix: "%image_articles%"
      upload_destination: "%kernel.project_dir%/public/images/articles"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      delete_on_update: false
      delete_on_remove: true
